locals {
  name = "${var.project}-${var.environment}"
}

# ---------------------------------------------------------------------------
# Master password - generated by Terraform, never hard-coded, never typed by
# a human. It only ever exists in Terraform state (protected by the
# encrypted, access-controlled S3 backend) and in the AWS Secrets Manager
# secret below.
# ---------------------------------------------------------------------------

resource "random_password" "master" {
  length           = 32
  special          = true
  override_special = "!#%^*()-_=+[]{}<>:?"
}

resource "aws_db_subnet_group" "this" {
  name       = "${local.name}-db-subnet-group"
  subnet_ids = var.db_subnet_ids

  tags = merge(var.tags, {
    Name = "${local.name}-db-subnet-group"
  })
}

# ---------------------------------------------------------------------------
# Security group - only the EKS application tier may reach MySQL, and RDS is
# never publicly accessible.
# ---------------------------------------------------------------------------

resource "aws_security_group" "rds" {
  name        = "${local.name}-rds-sg"
  description = "Allow MySQL access from the EKS application tier only"
  vpc_id      = var.vpc_id

  tags = merge(var.tags, {
    Name = "${local.name}-rds-sg"
  })
}

resource "aws_security_group_rule" "rds_ingress_mysql" {
  for_each = toset(var.allowed_security_group_ids)

  type                     = "ingress"
  from_port                = 3306
  to_port                  = 3306
  protocol                 = "tcp"
  security_group_id        = aws_security_group.rds.id
  source_security_group_id = each.value
  description              = "MySQL access from EKS application tier"
}

resource "aws_security_group_rule" "rds_egress_all" {
  type              = "egress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = aws_security_group.rds.id
  cidr_blocks       = ["0.0.0.0/0"]
  description       = "Allow outbound traffic for AWS service integrations (CloudWatch, monitoring)"
}

# ---------------------------------------------------------------------------
# Enhanced monitoring IAM role
# ---------------------------------------------------------------------------

data "aws_iam_policy_document" "rds_monitoring_assume" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["monitoring.rds.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "rds_monitoring" {
  count = var.monitoring_interval > 0 ? 1 : 0

  name               = "${local.name}-rds-monitoring-role"
  assume_role_policy = data.aws_iam_policy_document.rds_monitoring_assume.json

  tags = var.tags
}

resource "aws_iam_role_policy_attachment" "rds_monitoring" {
  count = var.monitoring_interval > 0 ? 1 : 0

  role       = aws_iam_role.rds_monitoring[0].name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}

# ---------------------------------------------------------------------------
# RDS MySQL instance
# ---------------------------------------------------------------------------

resource "aws_db_instance" "this" {
  identifier = "${local.name}-mysql"

  engine         = "mysql"
  engine_version = var.engine_version

  instance_class        = var.instance_class
  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_type          = var.storage_type
  storage_encrypted     = true

  db_name  = var.db_name
  username = var.master_username
  password = random_password.master.result

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.rds.id]
  publicly_accessible    = false

  multi_az = var.multi_az

  backup_retention_period = var.backup_retention_period
  backup_window           = var.backup_window
  maintenance_window      = var.maintenance_window
  copy_tags_to_snapshot   = true

  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${local.name}-mysql-final-snapshot"

  enabled_cloudwatch_logs_exports = ["error", "general", "slowquery"]

  monitoring_interval = var.monitoring_interval
  monitoring_role_arn = var.monitoring_interval > 0 ? aws_iam_role.rds_monitoring[0].arn : null

  performance_insights_enabled = var.performance_insights_enabled

  apply_immediately = var.apply_immediately

  tags = merge(var.tags, {
    Name = "${local.name}-mysql"
  })
}

# ---------------------------------------------------------------------------
# AWS Secrets Manager - single source of truth consumed by the AutoCare
# Helm chart's SecretProviderClass (autocare-deployment repo). The secret
# name/shape is a fixed cross-repo contract: it must stay exactly
# "autocare/<environment>/database" containing these 6 keys, because the
# chart's secretproviderclass.yaml pulls each one by name via jmesPath.
#
# REMEMBER_ME_KEY (Spring Security's remember-me cookie signing key) is
# bundled into this same secret rather than a second one - it is the only
# other application secret this platform needs today, and the pod already
# mounts this secret via a single SecretProviderClass object.
# ---------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "app" {
  name                    = "autocare/${var.environment}/database"
  description             = "AutoCare database credentials and app secrets for the ${var.environment} environment - synced into EKS via the Secrets Store CSI Driver"
  recovery_window_in_days = var.secret_recovery_window_days

  tags = merge(var.tags, {
    Name = "autocare-${var.environment}-database-secret"
  })
}

resource "aws_secretsmanager_secret_version" "app" {
  secret_id = aws_secretsmanager_secret.app.id
  secret_string = jsonencode({
    DB_HOST         = aws_db_instance.this.address
    DB_PORT         = tostring(aws_db_instance.this.port)
    DB_NAME         = aws_db_instance.this.db_name
    DB_USERNAME     = var.master_username
    DB_PASSWORD     = random_password.master.result
    REMEMBER_ME_KEY = var.app_remember_me_key
  })
}
